from email.mime.text import MIMEText
msg=MIMEText('hello','plain','utf-8')
from_address=input('From: ')
password=input('password: ')
to_addr=input('To: ')
#smtp_server=input('SMTP server: ')
import smtplib
#smtplib.SMTP_PORT=25
server=smtplib.SMTP('smtp.gmail.com:587')
#server.local_hostname()
#server.set_debuglevel(1)
#server.connect(''smtp.gmail.com'',465)
#server = smtplib.SMTP('smtp.example.com', 25)
#server.connect("smtp.gmail.com",587)
server.ehlo()
server.starttls()
server.ehlo()
server.login(from_address,password)
server.sendmail(from_address,[to_addr],msg.as_string())
server.quit()
